CREATE TABLE "departments" (
	"id" serial PRIMARY KEY NOT NULL,
	"code" varchar(2) NOT NULL,
	"name" varchar(256) NOT NULL,
	CONSTRAINT "departments_code_unique" UNIQUE("code")
);
--> statement-breakpoint
CREATE TABLE "issues" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" varchar(256) NOT NULL,
	"issue_description" varchar(1024),
	"impact" varchar(10) NOT NULL,
	"date_first_raised" date DEFAULT now(),
	"recommended_solution" varchar(1024),
	"status" varchar(10) DEFAULT 'Open' NOT NULL,
	"resolution_description" varchar(1024)
);
--> statement-breakpoint
CREATE TABLE "monthly_reports" (
	"id" serial PRIMARY KEY NOT NULL,
	"warehouse_id" varchar(256) NOT NULL,
	"department_id" integer NOT NULL,
	"project_id" integer NOT NULL,
	"issue_id" integer,
	"schedule_id" integer,
	"status" varchar(256),
	"report_date" date NOT NULL,
	"report_description" varchar(150),
	"summary" varchar(1024),
	"project_phase" varchar(256),
	"project_health" varchar(256),
	"approved_budget" integer NOT NULL,
	"total_spent" integer NOT NULL,
	"expected_features" integer,
	"completed_features" integer,
	"observations" varchar(2000),
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "monthly_reports_warehouse_id_unique" UNIQUE("warehouse_id")
);
--> statement-breakpoint
CREATE TABLE "hacc_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "hacc_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"rating" real,
	"imageUrl" varchar(512),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "projects" (
	"id" serial PRIMARY KEY NOT NULL,
	"code" varchar(4) NOT NULL,
	"name" varchar(256) NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"department_id" integer NOT NULL,
	"start_date" date NOT NULL,
	"projected_end_date" date NOT NULL,
	CONSTRAINT "projects_code_unique" UNIQUE("code")
);
--> statement-breakpoint
CREATE TABLE "schedules" (
	"id" serial PRIMARY KEY NOT NULL,
	"feature_name" varchar(255) NOT NULL,
	"deadline_date" date NOT NULL,
	"completed" boolean DEFAULT false NOT NULL,
	"status" varchar(10) DEFAULT 'open' NOT NULL,
	"date_closed" date
);
--> statement-breakpoint
ALTER TABLE "monthly_reports" ADD CONSTRAINT "monthly_reports_department_id_departments_id_fk" FOREIGN KEY ("department_id") REFERENCES "public"."departments"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "monthly_reports" ADD CONSTRAINT "monthly_reports_project_id_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."projects"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "monthly_reports" ADD CONSTRAINT "monthly_reports_issue_id_issues_id_fk" FOREIGN KEY ("issue_id") REFERENCES "public"."issues"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "monthly_reports" ADD CONSTRAINT "monthly_reports_schedule_id_schedules_id_fk" FOREIGN KEY ("schedule_id") REFERENCES "public"."schedules"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "projects" ADD CONSTRAINT "projects_department_id_departments_id_fk" FOREIGN KEY ("department_id") REFERENCES "public"."departments"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "name_idx" ON "hacc_post" USING btree ("name");